spring:
  application:
    name: example
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: validate
  mvc:
    problemdetails:
      enabled: true
logging:
  level:
    root: info
    io.github.pgatzka.example: info
    org.springframework.boot: warn